# Generated by Django 2.2.7 on 2019-11-26 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scienceworkshop',
            name='listener',
        ),
        migrations.AddField(
            model_name='scienceworkshop',
            name='description',
            field=models.CharField(default=' ', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='scienceworkshop',
            name='date_time',
            field=models.DateTimeField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='scienceworkshop',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='scienceworkshop',
            name='place',
            field=models.CharField(max_length=200, verbose_name='Место проведения'),
        ),
    ]
