# Generated by Django 2.2.7 on 2019-11-27 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops_app', '0002_auto_20191126_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceworkshop',
            name='max_listeners',
            field=models.IntegerField(null=True, verbose_name='Максимальное количество слушателей'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('science_workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops_app.ScienceWorkshop')),
            ],
        ),
    ]
