# Generated by Django 2.2.7 on 2019-11-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops_app', '0004_scienceworkshop_left_places'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='RegistrationOnSeminar',
        ),
    ]
