# Generated by Django 2.2.7 on 2019-11-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops_app', '0005_auto_20191127_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scienceworkshop',
            name='left_places',
        ),
        migrations.AddField(
            model_name='scienceworkshop',
            name='speaker',
            field=models.CharField(default=None, max_length=100, verbose_name='Лектор'),
        ),
        migrations.AlterField(
            model_name='scienceworkshop',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название семинара'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshops_app.UserType', verbose_name='Тип пользователя'),
        ),
    ]
